<a href="https://colab.research.google.com/github/msolowes-star/DI-Bootcamp/blob/main/Week4Day6DailyChalleneg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import files

uploaded = files.upload()

Saving Data Science Job Salary dataset.zip to Data Science Job Salary dataset.zip

In [6]:
import os

print(os.listdir())

['.config', 'Data Science Job Salary dataset.zip', 'sample_data']

In [7]:
import zipfile

with zipfile.ZipFile("Data Science Job Salary dataset.zip", "r") as zip_ref:
    zip_ref.extractall()

In [8]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        print(os.path.join(root, file))

./Data Science Job Salary dataset.zip
./.config/config_sentinel
./.config/.last_update_check.json
./.config/.last_opt_in_prompt.yaml
./.config/gce
./.config/.last_survey_prompt.yaml
./.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
./.config/default_configs.db
./.config/active_config
./.config/logs/2026.06.04/13.32.39.344962.log
./.config/logs/2026.06.04/13.32.38.346437.log
./.config/logs/2026.06.04/13.32.18.735754.log
./.config/logs/2026.06.04/13.31.42.499627.log
./.config/logs/2026.06.04/13.32.21.210570.log
./.config/logs/2026.06.04/13.32.02.654775.log
./.config/configurations/config_default
./Data Science Job Salary dataset/datascience_salaries.csv
./sample_data/anscombe.json
./sample_data/README.md
./sample_data/california_housing_train.csv
./sample_data/california_housing_test.csv
./sample_data/mnist_test.csv
./sample_data/mnist_train_small.csv

In [9]:
df = pd.read_csv("Data Science Job Salary dataset.zip")

In [10]:
df.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1171 non-null   int64
 1   job_title         1171 non-null   object
 2   job_type          1171 non-null   object
 3   experience_level  1171 non-null   object
 4   location          1171 non-null   object
 5   salary_currency   1171 non-null   object
 6   salary            1171 non-null   int64
dtypes: int64(2), object(5)
memory usage: 64.2+ KB

In [12]:
df.columns

Index(['Unnamed: 0', 'job_title', 'job_type', 'experience_level', 'location',
       'salary_currency', 'salary'],
      dtype='object')

**NORMALIZE THE SALARY COLUMN**

In [13]:
scaler = MinMaxScaler()

In [14]:
df["salary_normalized"] = scaler.fit_transform(df[["salary"]])

In [15]:
df[["salary", "salary_normalized"]].head()

   salary  salary_normalized
0  149000           0.601010
1  120000           0.454545
2   68000           0.191919
3  120000           0.454545
4  149000           0.601010

**Dimensionality Reduction (PCA)**

In [16]:
numeric_df = df.select_dtypes(include=np.number)

In [17]:
numeric_df.head()

   Unnamed: 0  salary  salary_normalized
0           0  149000           0.601010
1           2  120000           0.454545
2           3   68000           0.191919
3           4  120000           0.454545
4           5  149000           0.601010

In [18]:
standard = StandardScaler()

scaled_data = standard.fit_transform(numeric_df)

In [19]:
pca = PCA(n_components=2)

principal_components = pca.fit_transform(scaled_data)

In [20]:
pca_df = pd.DataFrame(
    principal_components,
    columns=["PC1", "PC2"]
)

pca_df.head()

        PC1       PC2
0  3.636314 -1.493641
1  2.376053 -1.471852
2  0.116216 -1.436780
3  2.376099 -1.468762
4  3.636428 -1.485916

**Group by experience level**

In [21]:
average_salary = df.groupby("experience_level")["salary"].mean()

print(average_salary)

experience_level
Entry        36111.111111
Executive    76076.923077
Mid          51786.885246
Senior       75088.033012
Name: salary, dtype: float64

In [22]:
salary_summary = df.groupby("experience_level")["salary"].agg(["mean", "median"])

salary_summary

                          mean   median
experience_level
Entry             36111.111111  30000.0
Executive         76076.923077  46000.0
Mid               51786.885246  51000.0
Senior            75088.033012  68000.0